### ISSUE TITLE
Solving Problems

### ISSUE THREAD

**Issue by MayankDimri** [code-chaser/leetcode-solutions#12]
I'll try to solve many problems as much as I can. Please assign the task to me.

**Comment by code-chaser** [comment]
- Done!
- NOTE: **Please avoid submitting solutions for problems whose solutions are already there**. You can submit it in different programming language though. And also, along with your PR attach links to your submissions on LeetCode as well, so that maintainers can verify them.

> **_Best Regards_**

**Comment by anmolrajsoni15** [comment]
Hello @code-chaser, I am also ready to work upon it. I would really appreciate it if you could assign me this issue so that can I can start contributing to this repo.
Thank you and have a great Hacktoberfest '22!

**Comment by code-chaser** [comment]
Hey @anmolrajsoni15 
- You can fork the repository and start solving as many problems as you can.
- Open a PR once you are done.
- Please see #18 

Thanks!

**Comment by anmolrajsoni15** [comment]
Hey @code-chaser 
I have opened the PR. I have tried to solve 11 leetcode problems. Kindly accept my PR.
Enjoyed working in your repo. Thanks for assigning the issue. I hope, I was able to help in your project.

**Comment by code-chaser** [comment]
- Closed in #46
