### ISSUE TITLE
Solving More Problems and Enhancing the repository

### ISSUE THREAD

**Issue by itsadityap** [code-chaser/leetcode-solutions#34]
I have already solved more then 410+ problems on Leetcode, would like to contribute to the repo.

**Comment by code-chaser** [comment]
Great, you can start!
- Please avoid any kind of redundancy.
- See #18 

Thanks!

**Comment by code-chaser** [comment]
Mention this issue in your PR, will close it with that PR.

**Comment by code-chaser** [comment]
- Closed in #36

**Comment by itsadityap** [comment]
Hey, I guess you forgot to add, hacktoberfest-accepted tag , while merging the the branch.
