### ISSUE TITLE
Solve Problems in Java

### ISSUE THREAD

**Issue by Sabyasachi-Seal** [code-chaser/leetcode-solutions#58]
Want to Add solutions to these questions:

Longest Common Substring: https://www.geeksforgeeks.org/longest-common-substring-dp-29/
Longest Common Subsequence: https://leetcode.com/problems/longest-common-subsequence/
House Robber II : https://leetcode.com/problems/house-robber-ii/
Minimum Swaps To Make Sequences Increasing :https://leetcode.com/problems/minimum-swaps-to-make-sequences-increasing/

**Comment by code-chaser** [comment]
You can check the repository if these problems have not yet been solved, you can solve them, and open a PR.

**Comment by Sabyasachi-Seal** [comment]
Yes, I checked. The solutions to these are not present. I will work on them and send a PR asap.

**Comment by code-chaser** [comment]
Closed in #69
