### ISSUE TITLE
[ADD]-Submissions

### ISSUE THREAD

**Issue by code-chaser** [code-chaser/leetcode-solutions#6]
- Add all submissions by [code-chaser](https://leetcode.com/code-chaser/) of all problems;
- All verdicts;

**Comment by prof-sergio-marquina** [comment]
I can work on this

**Comment by prof-sergio-marquina** [comment]
Assign me

**Comment by code-chaser** [comment]
Done!

**Comment by code-chaser** [comment]
Closed by @prof-sergio-marquina in #7
